language: node_js
node_js:
  - "10.15.1"
  - "10.15.0"
  - "10.14.2"
  - "10.13.0"
addons:
     code_climate:
         repo_token:
             secure: f5e95958c436d6e05bbf0102065d1ce9c85e3f67c16c0cd544eec05095948a31
script: 
  - istanbul cover npm test --reporter lcovonly -- -R spec
  - codecov
install:
  - npm install -g codecov
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
